apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paymentservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: 'softtekcoeapisms/paymentservice:1.0'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    name: paymentservice
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: paymentservice
  type: ClusterIP